import { Pokemon } from "./pokemon";

export const POKEMON : Pokemon[]  = [
    {
        id      :   1,
        num     :   308,
        pv      :   60,
        atk     :   60,
        def     :   75,
        atkSpe  :   60,
        defSpe  :   75,
        vit     :   80,
        nom     :   "Charmina",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/308.png",
        types   :   ["Combat", "Psy"],
        created :   new Date()
    },
    {
        id      :   2,
        num     :   448,
        pv      :   70,
        atk     :   110,
        def     :   70,
        atkSpe  :   115,
        defSpe  :   70,
        vit     :   90,
        nom     :   "Lucario",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/448.png",
        types   :   ["Combat", "Acier"],
        created :   new Date()
    },
    {
        id      :   3,
        num      :   479,
        pv      :   50,
        atk     :   50,
        def     :   77,
        atkSpe  :   95,
        defSpe  :   77,
        vit     :   91,
        nom     :   "Motisma",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/479.png",
        types   :   ["Electrik", "Spectre"],
        created :   new Date()
    },
    {
        id      :   4,
        num      :   26,
        pv      :   60,
        atk     :   90,
        def     :   55,
        atkSpe  :   90,
        defSpe  :   80,
        vit     :   110,
        nom     :   "Raichu",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/026.png",
        types   :   ["Electrik"],
        created :   new Date()
    },
    {
        id      :   5,
        num      :   59,
        pv      :   90,
        atk     :   110,
        def     :   80,
        atkSpe  :   100,
        defSpe  :   80,
        vit     :   95,
        nom     :   "Arcanin",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/059.png",
        types   :   ["Feu"],
        created :   new Date()
    },
    {
        id      :   6,
        num      :   6,
        pv      :   78,
        atk     :   84,
        def     :   78,
        atkSpe  :   109,
        defSpe  :   85,
        vit     :   100,
        nom     :   "Dracaufeu",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/006.png",
        types   :   ["Feu", "Vol"],
        created :   new Date()
    },
    {
        id      :   7,
        num      :   407,
        pv      :   60,
        atk     :   70,
        def     :   65,
        atkSpe  :   125,
        defSpe  :   105,
        vit     :   90,
        nom     :   "Roserade",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/407.png",
        types   :   ["Plante", "Poison"],
        created :   new Date()
    },
    {
        id      :   8,
        num      :   359,
        pv      :   65,
        atk     :   130,
        def     :   60,
        atkSpe  :   75,
        defSpe  :   60,
        vit     :   75,
        nom     :   "Absol",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/359.png",
        types   :   ["Ténèbres"],
        created :   new Date()
    },
    {
        id      :   9,
        num      :   373,
        pv      :   95,
        atk     :   135,
        def     :   80,
        atkSpe  :   110,
        defSpe  :   80,
        vit     :   100,
        nom     :   "Drattak",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/373.png",
        types   :   ["Dragon", "Vol"],
        created :   new Date()
    },
    {
        id      :   10,
        num      :   376,
        pv      :   80,
        atk     :   135,
        def     :   130,
        atkSpe  :   95,
        defSpe  :   90,
        vit     :   70,
        nom     :   "Métalosse",
        picture :   "https://www.pokemontrash.com/pokedex/images/sugimori/376.png",
        types   :   ["Acier", "Psy"],
        created :   new Date()
    }
]